color0 #1c3436
color1 #fd4663
color2 #85e9e1
color3 #8cbfe2
color4 #9399db
color5 #93ece4
color6 #96c7e9
color7 #f2f3f3
color8 #61716f
color9 #fd4663
color10 #85e9e1
color11 #8cbfe2
color12 #9399db
color13 #93ece4
color14 #96c7e9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #152728
background            #152728
foreground            #f2f3f3
selection_foreground  #afb6b6
selection_background  #1c3436
active_border_color   #85e9e1
inactive_border_color #1c3436
url_color             #85e9e1

active_tab_foreground   #182524
active_tab_background   #85e9e1
inactive_tab_foreground #afb6b6
inactive_tab_background #1c3436
cursor_trail_color      #afb6b6
